### ISSUE TITLE
Convert temperature values to a color temperature value for the lightbulb.

### ISSUE THREAD

**Issue by jkulka** [ambient-jrc/ambient-lightbulb#2]
Given a temperature value, return a color temperature value for the lightbulb.
Blue for cold, orange for hot. 

Do work in branch called issue-02

**Comment by calmaruy** [comment]
If I am not mistaken, our model of bulb cannot change color. Only brightness. The code submitted is a pseudo version of what this function should do. This is under the assumption that we already data mined the temperature value and have it stored as the variable 'temp'.
[yeelight_pseudo.txt](https://github.com/ambient-jrc/ambient-lightbulb/files/3015831/yeelight_pseudo.txt)

**Comment by jkulka** [comment]
It doesn't have color in terms of RGB, but it does have color temperature control (From blue to orange, blue being morning lights and orange for night lights)

**Comment by calmaruy** [comment]
[temp_brightness.txt](https://github.com/ambient-jrc/ambient-lightbulb/files/3021262/temp_brightness.txt)
Most likely will change for the temp variable to be attained inside of the function instead of being passed in by calling get_temp
